require('plugins')

require('autocmd')
require('settings')
require('keys')

require('colors')
require('statusline')
require('buffer')
require('nvtree')
require('tree')
require('dashboard')
require('indent')
require('tel')
require('pairs')
require('lightbulb')
require('scroll')
require('lsptrouble')
require('term')
require('git')
require('outline')
require('diaal')

require('lsp-compe')
require('lsp-kind')
require('lsp')
