#!/bin/sh

color=$(colorpicker)
convert -size 100x100 xc:$color /tmp/color.png

notify-send --icon=/tmp/color.png --app-name="$color" "color coppied to clipboard"
echo -n $color | xclip -selection clipboard

rm /tmp/color.png
