#!/bin/sh
seven=$(xmodmap -pke | grep "keycode  16" | awk '{print $5}')

toggle() {
    if [ "$seven" = "ampersand" ]; then
      setxkbmap fr
    else
      setxkbmap us
    fi 
}

case $BLOCK_BUTTON in
  1) toggle ;;
esac

if [ "$seven" = "ampersand" ]; then
  echo " us"
else
  echo " fr"
fi
