#!/bin/sh

export WINEPREFIX=$HOME/osu/
export WINEARCH=win64
export STAGING_AUDIO_PERIOD=6600
export STAGING_AUDIO_DURATION=7000
# export STAGING_AUDIO_PERIOD=10000
# export STAGING_AUDIO_DURATION=20000
# export STAGING_AUDIO_PERIOD=7000
# export STAGING_AUDIO_DURATION=8000
export PATH=/opt/wine-osu/bin:$PATH
export vblank_mode=0

$HOME/docs/winestreamproxy/start.sh &

wine ~/osu/osufolder/osu\!.exe "$@" && osukill
