#!/bin/sh

export WINEPREFIX=$HOME/osu/
export WINEARCH=win64
# export STAGING_AUDIO_PERIOD=6600
# export STAGING_AUDIO_DURATION=7000
export STAGING_AUDIO_PERIOD=20000
export STAGING_AUDIO_DURATION=30000
export PATH=/opt/wine-osu/bin:$PATH
export vblank_mode=0

wine $HOME/git/wine-discord-ipc-bridge/winediscordipcbridge.exe &
sleep 3
wine ~/osu/osufolder/osu\!.exe "$@" && osukill
