#!/bin/sh

export WINEPREFIX=$HOME/osu
export WINEARCH=win64
export STAGING_AUDIO_PERIOD=6600
export STAGING_AUDIO_DURATION=7000
export PATH=/opt/wine-osu/bin:$PATH
export vblank_mode=0

if [ ! "$(pgrep 'osu!.exe')" ]; then
    wineserver -k
fi
