#!/bin/sh

DMENUOPTS="-x 6 -y 6 -z 1920 -i"

choice=$(printf "poweroff\\nreboot\\nexit" | dmenu $DMENUOPTS -p "powermenu :")
case "$choice" in
    poweroff) doas poweroff ;;
    reboot) doas reboot ;;
    exit) kill -15 $(pidof hydra) ;;
esac
