#!/bin/sh

single(){
    $HOME/.screenlayout/single.sh
}

double() {
    $HOME/.screenlayout/double.sh
}

mirror(){
    $HOME/.screenlayout/mirror.sh
}

case $1 in
    --single) single ;;
    --double) double ;;
    --mirror) mirror ;;
    -s) single ;;
    -d) double ;;
    -m) mirror ;;
    *) echo "error : --single --double --mirror" && exit 1 ;;
esac
